from enum import IntEnum

class Instruction(IntEnum):
    HALT = 0
    ICONST = 1 # INT
    FLCONST = 2 # FLOAT
    TCONST = 3 # TIME
    OCONST = 4 # OBJECT
    FOCONST = 5 # FORCE
    DISPLAY = 6 # DISPLAY SCREEN
    GSTOREI = 7 # STORE GLOBAL INT, TIME OR FLOAT
    GSTOREO = 8 # STORE GLOBAL OBJECT
    GSTOREF = 9 # STORE GLOBAL FORCE
    GLOADI = 10 # LOAD GLOBAL INT, TIME OR FLOAT
    GLOADO = 11 # LOAD GLOBAL OBJECT
    GLOADF = 12 # LOAD GLOBAL FORCE

    GDRAW_OBJECT = 13 # DRAW OBJECT - POINTER TO MEM
    GAPPLY_FORCE = 14